### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by dsanying** [prinsss/hexo-hide-posts#13]
安装后hexo g时
```git
TypeError: Cannot read property 'includes' of null
    at Hexo.<anonymous> (D:\hexo\node_modules\hexo-hide-posts\index.js:125:13)
    at Hexo.tryCatcher (D:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\hexo\node_modules\bluebird\js\release\method.js:15:34)
    at D:\hexo\node_modules\hexo\lib\extend\filter.js:62:52
    at tryCatcher (D:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Object.gotValue (D:\hexo\node_modules\bluebird\js\release\reduce.js:166:18)
    at Object.gotAccum (D:\hexo\node_modules\bluebird\js\release\reduce.js:155:25)
    at Object.tryCatcher (D:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\hexo\node_modules\bluebird\js\release\promise.js:547:31)
    at Promise._settlePromise (D:\hexo\node_modules\bluebird\js\release\promise.js:604:18)
    at Promise._settlePromise0 (D:\hexo\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (D:\hexo\node_modules\bluebird\js\release\promise.js:729:18)
    at _drainQueueStep (D:\hexo\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (D:\hexo\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (D:\hexo\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\hexo\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

```

**Comment by prinsss** [comment]
插件已更新至 0.1.1，如果问题依然存在请 reopen
