### ISSUE TITLE
hexo g  error

### ISSUE THREAD

**Issue by lossv** [prinsss/hexo-hide-posts#15]
➜  hexo hexo g
INFO  Start processing
INFO  2 posts are marked as hidden
WARN  categories/index.html won't be rendered.
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'bind' of undefined
    at Hexo.<anonymous> (/home/haoyue/文档/Web/hexo/node_modules/hexo-hide-posts/index.js:59:30)
请问是哪里有错误呢？？？
我的hexo 版本是4.2的

**Comment by prinsss** [comment]
运行 `hexo g --debug`，把输出的调试信息贴上来看看

（不要直接粘贴到这里，用 https://paste.ubuntu.com/ ）

**Comment by lossv** [comment]
您好 调试信息如下

hexo git:(master) ✗ hexo g -debug
INFO  Start processing
INFO  0 posts are marked as hidden
WARN  categories/index.html won't be rendered.
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read property 'bind' of undefined
    at Hexo.<anonymous> (/home/haoyue/文档/Web/hexo/node_modules/hexo-hide-posts/index.js:59:30)
    at Hexo.tryCatcher (/home/haoyue/文档/Web/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/haoyue/文档/Web/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /home/haoyue/文档/Web/hexo/node_modules/hexo/lib/hexo/index.js:390:22
    at tryCatcher (/home/haoyue/文档/Web/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/home/haoyue/文档/Web/hexo/node_modules/bluebird/js/release/map.js:68:38)
    at MappingPromiseArray.PromiseArray._iterate (/home/haoyue/文档/Web/hexo/node_modules/bluebird/js/release/promise_array.js:115:31)
    at MappingPromiseArray.init (/home/haoyue/文档/Web/hexo/node_modules/bluebird/js/release/promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (/home/haoyue/文档/Web/hexo/node_modules/bluebird/js/release/map.js:37:10)
    at _drainQueueStep (/home/haoyue/文档/Web/hexo/node_modules/bluebird/js/release/async.js:97:12)
    at _drainQueue (/home/haoyue/文档/Web/hexo/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/haoyue/文档/Web/hexo/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues (/home/haoyue/文档/Web/hexo/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:456:21)

**Comment by prinsss** [comment]
插件已更新至 0.1.1，如果问题依然存在请 reopen
